@TemplateProject_HostAddress = https://localhost:7215

POST {{TemplateProject_HostAddress}}/api/usuarios
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "email": "kevin.barre92@yahoo.com",
  "password": "Peorparaelsol2026#"
}

###

POST {{TemplateProject_HostAddress}}/api/usuarios/login
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "email": "kevin.barre92@yahoo.com",
  "password": "Peorparaelsol2026#"
}
